package com.roadlink.domain

import com.roadlink.domain.Canonical.toHex
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-language contract test.
 *
 * Every expected value below was generated by running the backend's
 * `app/canonical.py` directly. If Kotlin and Python ever disagree, the relay
 * would forward packets the backend silently marks sig_valid=false, and the
 * only visible symptom would be a column in the database. That failure is far
 * too quiet to leave untested, so it is pinned here and fails the JVM suite.
 *
 * Regenerate the vectors from the Python implementation - never by copying
 * whatever Kotlin currently produces, which would make the test circular.
 */
class CanonicalTest {

    @Test
    fun `typical packet matches the python canonical string and signature`() {
        val canonical = Canonical.canonicalString(
            v = 1,
            eventId = "9f2c1d4e-7a3b-4c5d-8e6f-0a1b2c3d4e5f",
            riderId = "rl_7f3a91c4",
            createdAt = 1755763200123L,
            lat = 17.4401,
            lng = 78.3489,
            accuracyMetres = 12,
            confidence = 82,
            triggers = listOf("peak_g", "inactivity"),
            simulated = true,
        )
        assertEquals(
            "v=1|event_id=9f2c1d4e-7a3b-4c5d-8e6f-0a1b2c3d4e5f|rider_id=rl_7f3a91c4|" +
                "created_at=1755763200123|lat=17.4401000|lng=78.3489000|acc_m=12|conf=82|" +
                "trigger=inactivity,peak_g|simulated=1",
            canonical,
        )
        assertEquals("GAcioj4vP5N7Y1ZwjE/M6A==", Canonical.sign(canonical))
    }

    @Test
    fun `absent location and empty triggers serialise as empty fields`() {
        val canonical = Canonical.canonicalString(
            v = 1,
            eventId = "00000000-0000-4000-8000-000000000001",
            riderId = "rl_abc",
            createdAt = 0L,
            lat = null,
            lng = null,
            accuracyMetres = null,
            confidence = 0,
            triggers = emptyList(),
            simulated = false,
        )
        assertEquals(
            "v=1|event_id=00000000-0000-4000-8000-000000000001|rider_id=rl_abc|created_at=0|" +
                "lat=|lng=|acc_m=|conf=0|trigger=|simulated=0",
            canonical,
        )
        assertEquals("rOzvtDKSR1PvVuhHM8M4vg==", Canonical.sign(canonical))
    }

    @Test
    fun `negative coordinates round trip and triggers are sorted not preserved`() {
        val canonical = Canonical.canonicalString(
            v = 1,
            eventId = "11111111-2222-4333-8444-555555555555",
            riderId = "rl_neg",
            createdAt = 1700000000000L,
            lat = -33.8688197,
            lng = -151.2092955,
            accuracyMetres = 0,
            confidence = 100,
            // deliberately unsorted on the way in
            triggers = listOf("zebra", "alpha", "middle"),
            simulated = true,
        )
        assertTrue("triggers must be sorted", canonical.contains("trigger=alpha,middle,zebra"))
        assertEquals(
            "v=1|event_id=11111111-2222-4333-8444-555555555555|rider_id=rl_neg|" +
                "created_at=1700000000000|lat=-33.8688197|lng=-151.2092955|acc_m=0|conf=100|" +
                "trigger=alpha,middle,zebra|simulated=1",
            canonical,
        )
        assertEquals("hg35UnpBgwmX5scNhIWUXg==", Canonical.sign(canonical))
    }

    /**
     * The case that actually caught a bug: a tiny negative longitude rounds to
     * zero, and C's printf keeps the minus sign while BigDecimal drops it.
     * Without the explicit negative-zero handling in Canonical.fmtCoord this
     * produces "0.0000000" and every signature on such a packet is wrong.
     */
    @Test
    fun `value rounding to negative zero keeps its sign like printf`() {
        val canonical = Canonical.canonicalString(
            v = 1,
            eventId = "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
            riderId = "rl_round",
            createdAt = 1755763200999L,
            lat = 12.123456789012345,
            lng = -0.000000049999999,
            accuracyMetres = 99999,
            confidence = 50,
            triggers = listOf("peak_g"),
            simulated = false,
        )
        assertTrue("negative zero must keep its sign", canonical.contains("lng=-0.0000000"))
        assertTrue("excess precision must round to 7dp", canonical.contains("lat=12.1234568"))
        assertEquals(
            "v=1|event_id=aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee|rider_id=rl_round|" +
                "created_at=1755763200999|lat=12.1234568|lng=-0.0000000|acc_m=99999|conf=50|" +
                "trigger=peak_g|simulated=0",
            canonical,
        )
        assertEquals("ht4SK8pDJr5bp+pyimPV1w==", Canonical.sign(canonical))
    }

    // -------------------------------------------------------------- event_ref

    @Test
    fun `event_ref matches the python implementation and the spike beacon`() {
        assertEquals(
            "11e594f481958c10",
            Canonical.eventRefHex("00000000-0000-4000-8000-000000000001"),
        )
        assertEquals(
            "d6bc115bf3d492a7",
            Canonical.eventRefHex("9f2c1d4e-7a3b-4c5d-8e6f-0a1b2c3d4e5f"),
        )
        assertEquals(8, Canonical.eventRef("anything").size)
    }

    @Test
    fun `event_ref does not leak the event id`() {
        val eventId = "9f2c1d4e-7a3b-4c5d-8e6f-0a1b2c3d4e5f"
        val ref = Canonical.eventRefHex(eventId)
        assertTrue(
            "the raw event_id must not be recoverable from the broadcast reference",
            !eventId.replace("-", "").contains(ref),
        )
    }

    // -------------------------------------------------------------- signing

    @Test
    fun `signing an event object agrees with signing its fields`() {
        val event = EmergencyEvent(
            eventId = "9f2c1d4e-7a3b-4c5d-8e6f-0a1b2c3d4e5f",
            riderId = "rl_7f3a91c4",
            createdAt = 1755763200123L,
            lat = 17.4401,
            lng = 78.3489,
            accuracyMetres = 12,
            confidence = 82,
            triggers = listOf("peak_g", "inactivity"),
            origin = EventOrigin.MANUAL_TEST,
            signature = null,
        )
        assertEquals("GAcioj4vP5N7Y1ZwjE/M6A==", Canonical.sign(event))
    }

    @Test
    fun `mutating any signed field changes the signature`() {
        val event = EmergencyEvent(
            eventId = "9f2c1d4e-7a3b-4c5d-8e6f-0a1b2c3d4e5f",
            riderId = "rl_7f3a91c4",
            createdAt = 1755763200123L,
            lat = 17.4401,
            lng = 78.3489,
            accuracyMetres = 12,
            confidence = 82,
            triggers = listOf("peak_g", "inactivity"),
            origin = EventOrigin.MANUAL_TEST,
            signature = null,
        )
        val original = Canonical.sign(event)
        assertNotEquals(original, Canonical.sign(event.copy(confidence = 83)))
        assertNotEquals(original, Canonical.sign(event.copy(lat = 17.4402)))
        // origin flips `simulated`, which is inside the signature on purpose:
        // a simulated event cannot be relabelled as real without resigning.
        assertNotEquals(original, Canonical.sign(event.copy(origin = EventOrigin.REAL_SENSOR)))
    }

    @Test
    fun `delivery bookkeeping is outside the signature`() {
        val event = EmergencyEvent(
            eventId = "9f2c1d4e-7a3b-4c5d-8e6f-0a1b2c3d4e5f",
            riderId = "rl_7f3a91c4",
            createdAt = 1755763200123L,
            lat = 17.4401,
            lng = 78.3489,
            accuracyMetres = 12,
            confidence = 82,
            triggers = listOf("peak_g", "inactivity"),
            origin = EventOrigin.MANUAL_TEST,
            signature = null,
        )
        val signature = Canonical.sign(event)
        // This is what lets the rider and any number of relays submit the same
        // byte-identical packet without a signature mismatch.
        val afterDelivery = event.copy(
            state = DeliveryState.DELIVERY_ATTEMPT,
            activeTransport = TransportKind.SIMULATED_RELAY,
            attemptCount = 7,
            lastError = "relay vanished",
        )
        assertEquals(signature, Canonical.sign(afterDelivery))
    }

    @Test
    fun `hex helper is lower case and zero padded`() {
        assertEquals("000f10ff", byteArrayOf(0, 15, 16, -1).toHex())
    }
}
